  
name: ci/cd dev branch
  
on:
  push:
    branches: [ dev ]

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Login-to-Docker Hub
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: sharefm/dev-react-redux:latest


        
  pull-deploy-image:
    runs-on: ubuntu-latest
    needs: docker-build-push
    steps:    
    -
      name: Login-to-Docker Hub
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: ls
      run: ls -lat
    -
      name: pwd
      run: echo $PWD
    
    -
      name: Build and push
      run: kubectl apply -f k8s.yml
      
