  
name: ci/cd dev branch
  
on:
  push:
    branches: [ dev ]

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Login-to-Docker Hub
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - 
      name: checkout      
      uses: actions/checkout@v4

    -
      name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: sharefm/dev-react-redux:latest

  
  Test-code:
      runs-on: ubuntu-latest
      needs: docker-build-push
      steps:          
      -
        name: test-step
        run: echo "test not ready"

        
  pull-deploy-image:
    runs-on: ubuntu-latest
    needs: Test-code
    steps:    
    
    - 
      name: checkout      
      uses: actions/checkout@v4

    - 
      name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    -
      name: kube-config
      run: az aks get-credentials --resource-group dev-rg --name dev-aks-cluster 
    
    -
      name: Build and push
      run: kubectl apply -f k8s.yml
      
