  
name: ci/cd main branch
  
on:
  push:
    branches: [ main ]

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Login-to-Docker Hub
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: sharefm/main-react-redux:latest


        
  Test-code:
    runs-on: ubuntu-latest
    needs: docker-build-push
    steps:          
    -
      name: test-step
      run: echo "test not ready"        


        
  pull-deploy-image:
    runs-on: ubuntu-latest
    needs: Test-code
    steps:    
    -
      name: Login-to-Docker Hub
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    -
      name: Build and push
      run: kubectl apply -f /app/k8s.yml
      
